## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [92]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [93]:
n = int(input())
np.array([1, 2, 3]*n)

7


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [94]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [95]:
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[:, 0] = 1
matrix[9, :] = 1
matrix[:, 9] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [96]:
matrix = np.zeros((8, 8))
matrix[0 :: 2, 0 :: 2] = 1
matrix[1 :: 2, 1 :: 2] = 1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [97]:
%%time
n = int(input())
matr1, matr2 = np.zeros((n, n)), np.zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        matr1[i, j] = i
        matr2[j, i] = i
matr1 + matr2

5
CPU times: total: 0 ns
Wall time: 2.6 s


array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [98]:
vector1 = np.array([0, 1, 2, 3])
vector2 = np.array([0, 1, 2, 3])

matrix1 = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [8, 7, 6, 5], 
    [4, 3, 2, 1]
])
matrix2 = np.array([
    [1, 1, 1, 1], 
    [1, 1, 1, 1], 
    [1, 1, 1, 1], 
    [1, 1, 1, 1]
])

print(str(np.vdot(vector1, vector2)) + ' - перемножение вектора на вектор')
print('-------------------------------------')
print(str(np.dot(matrix1, vector1)) + ' - перемножение матрицы на вектор')     
print('-------------------------------------')
print(str(np.dot(matrix1, matrix2)) + ' - перемножение матрицы на матрицу')  

14 - перемножение вектора на вектор
-------------------------------------
[20 44 34 10] - перемножение матрицы на вектор
-------------------------------------
[[10 10 10 10]
 [26 26 26 26]
 [26 26 26 26]
 [10 10 10 10]] - перемножение матрицы на матрицу


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [99]:
cos_x = np.cos(np.linspace(0, 1, int(1 / 0.05 + 1)))
sin_x = np.sin(np.linspace(0, 1, int(1 / 0.05 + 1)))
list(cos_x) + list(sin_x)

[1.0,
 0.9987502603949663,
 0.9950041652780258,
 0.9887710779360422,
 0.9800665778412416,
 0.9689124217106447,
 0.955336489125606,
 0.9393727128473789,
 0.9210609940028851,
 0.9004471023526769,
 0.8775825618903728,
 0.8525245220595057,
 0.8253356149096782,
 0.7960837985490559,
 0.7648421872844884,
 0.7316888688738209,
 0.6967067093471654,
 0.6599831458849821,
 0.6216099682706644,
 0.5816830894638835,
 0.5403023058681398,
 0.0,
 0.04997916927067833,
 0.09983341664682815,
 0.14943813247359924,
 0.19866933079506122,
 0.24740395925452294,
 0.2955202066613396,
 0.3428978074554514,
 0.3894183423086505,
 0.43496553411123023,
 0.479425538604203,
 0.5226872289306592,
 0.5646424733950355,
 0.6051864057360395,
 0.6442176872376911,
 0.6816387600233341,
 0.7173560908995228,
 0.7512804051402927,
 0.7833269096274834,
 0.8134155047893737,
 0.8414709848078965]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [100]:
a = (3 - (-1)) * np.random.random_sample((3, 5)) + (-1)
a

array([[ 1.28949837, -0.46678676, -0.17075933,  1.29879991,  0.47613839],
       [ 0.46908061, -0.81832546,  0.1823211 , -0.48312206,  2.74795163],
       [-0.66470271,  1.65498817, -0.99548882,  0.19533942, -0.59091159]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [101]:
summa = np.sum(a)
rows = np.sum(a, axis = 1)
columns = np.sum(a, axis = 0)
avg = np.mean(a, axis = 1)
disp = np.var(a, axis = 1)
otkl = np.std(a, axis = 1)
print(summa, ' - сумму всех элементов матрицы')
print(rows, ' - сумму внутри строк матрицы')
print(columns, ' - сумму внутри столбцов матрицы')
print(avg, ' - среднее значение для каждой строки')
print(disp, ' - дисперсия для каждой строки')
print(otkl, ' - стандартное отклонение для каждой строки')

4.124020854587823  - сумму всех элементов матрицы
[ 2.42689058  2.09790581 -0.40077553]  - сумму внутри строк матрицы
[ 1.09387627  0.36987595 -0.98392705  1.01101726  2.63317842]  - сумму внутри столбцов матрицы
[ 0.48537812  0.41958116 -0.08015511]  - среднее значение для каждой строки
[0.52909682 1.56546749 0.90540466]  - дисперсия для каждой строки
[0.72739041 1.25118643 0.95152754]  - стандартное отклонение для каждой строки


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [102]:
for i in range(len(a)):
    a[i, :] = (a[i, :] - np.mean(a[i])) / np.std(a[i])
a

array([[ 1.10548646, -1.30901488, -0.90204302,  1.11827401, -0.01270257],
       [ 0.03956201, -0.98938622, -0.18962806, -0.72147779,  1.86093007],
       [-0.61432546,  1.82353448, -0.96196239,  0.28952869, -0.53677531]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [103]:
col = a[:, 2]
sort = col.argsort()
a = a[sort]
a

array([[-0.61432546,  1.82353448, -0.96196239,  0.28952869, -0.53677531],
       [ 1.10548646, -1.30901488, -0.90204302,  1.11827401, -0.01270257],
       [ 0.03956201, -0.98938622, -0.18962806, -0.72147779,  1.86093007]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [104]:
matr_b = np.dot(np.transpose(a), a)
matr_c = np.dot(a, np.transpose(a))
print(matr_b, ' - матрица В')
print(matr_c, ' - матрица С')

[[ 1.60106125 -2.606484   -0.41374042  1.02982882  0.38933434]
 [-2.606484    6.01768304 -0.38576846 -0.22205158 -2.803379  ]
 [-0.41374042 -0.38576846  1.77501206 -1.15043454  0.17493136]
 [ 1.02982882 -0.22205158 -1.15043454  1.85489383 -1.51223653]
 [ 0.38933434 -2.803379    0.17493136 -1.51223653  3.75134983]]  - матрица В
[[ 5.         -1.86783995 -2.8538586 ]
 [-1.86783995  5.          0.67946076]
 [-2.8538586   0.67946076  5.        ]]  - матрица С


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [107]:
np.sum(np.diagonal(matr_b)) + np.sum(np.diagonal(matr_c))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg).


In [108]:
# print(np.linalg.det(a)) #матрица а не квадратного вида
print(np.linalg.det(matr_b), ' - определитель матрицы В')
print(np.linalg.det(matr_c), ' - определитель матрицы С')
print(np.linalg.matrix_rank(a), ' - ранг матрицы A')
print(np.linalg.matrix_rank(matr_b), ' - ранг матрицы В')
print(np.linalg.matrix_rank(matr_c), ' - ранг матрицы C')
w_b, v_b = np.linalg.eig(matr_b)
w_c, v_b = np.linalg.eig(matr_c)
print(w_b, ' - спектр матрицы В')
print(w_c, ' - спектр матрицы С')

# У всех матриц одинаковый ранг и равен трем.
# При перемножении транспонированной матрицы на исходную марицу и исходной на транспонированную ранг не меняется.
# При таком перемножении будет меняться определитель и спектр полученной матрицы.

3.758666554982447e-30  - определитель матрицы В
71.76879113969105  - определитель матрицы С
3  - ранг матрицы A
3  - ранг матрицы В
3  - ранг матрицы C
[8.74552905e+00 4.38153249e+00 1.87293846e+00 7.23635992e-16
 2.15584295e-16]  - спектр матрицы В
[8.74552905 1.87293846 4.38153249]  - спектр матрицы С


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [109]:
np.random.seed(1032201200)
np.random.randint(9)

8

In [110]:
def func8(x):
    return (2*x) / (2*x + 1)
a, b = 0, 2
dx = 0.0001
def solve_integr(func, dx):
    n = int((b - a) / dx)
    x_step = np.linspace(a, b, n)
    meth1 = dx * np.sum(func(x_step))
    meth2 = dx / 2 * (func(x_step[0]) + 2 * np.sum(func(x_step[1:-1])) + func(x_step[-1]))
    meth3 = dx / 3 * (func(x_step[0]) + 2 * np.sum(func(x_step[2:-1:2])) + 4 * np.sum(func(x_step[1:-2:2])) + func(x_step[-1]))
    return meth1, meth2, meth3


print('Решение интеграла 8:', solve_integr(func8, dx)[0], ' (метод прямоугольников)')
print('Решение интеграла 8:', solve_integr(func8, dx)[1], ' (метод трапеций)')
print('Решение интеграла 8:', solve_integr(func8, dx)[2], ' (метод Симпсона)')
print('-----------------------------------------------------------------')


Решение интеграла 8: 1.1952612781306806  (метод прямоугольников)
Решение интеграла 8: 1.1952212781306806  (метод трапеций)
Решение интеграла 8: 1.1951946131974343  (метод Симпсона)
-----------------------------------------------------------------


In [113]:
def func9(x):
    return 1 / np.sqrt(2 + 3 * x - 2 * x ** 2, where=x != 2)
a, b = 3/4, 2
dx = 0.0001
def solve_integr(func, dx):
    n = int((b - a) / dx)
    x_step = np.linspace(a, b, n)
    meth1 = dx * np.sum(func(x_step))
    meth2 = dx / 2 * (func(x_step[0]) + 2 * np.sum(func(x_step[1:-1])) + func(x_step[-1]))
    meth3 = dx / 3 * (func(x_step[0]) + 2 * np.sum(func(x_step[2:-1:2])) + 4 * np.sum(func(x_step[1:-2:2])) + func(x_step[-1]))
    return meth1, meth2, meth3

print('Решение интеграла 9:', solve_integr(func9, dx)[0], ' (метод прямоугольников)')
print('Решение интеграла 9:', solve_integr(func9, dx)[1],' (метод трапеций)')
print('Решение интеграла 9:', solve_integr(func9, dx)[2],  ' (метод Симпсона)')

Решение интеграла 9: 1.1041419998928388  (метод прямоугольников)
Решение интеграла 9: 1.1041172156215913  (метод трапеций)
Решение интеграла 9: 1.1032101773676126  (метод Симпсона)


In [115]:
# При уменьшении dx уменьшается шаг и увеличенивается число точек x_step.
# Таким образом, увеличивается точность решения.